apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: watchpost-cargo-monitoring
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchBinaries:
            - operator: In
              values:
                - "/usr/bin/cargo"
                - "/usr/bin/rustc"
                - "/usr/bin/cc"
                - "/usr/bin/ld"
                - "/usr/local/bin/cargo"
                - "/usr/local/bin/rustc"
          matchActions:
            - action: Post
