apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: watchpost-flatpak-escape
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchArgs:
            - index: 0
              operator: Prefix
              values:
                - "/home/"
                - "/etc/"
                - "/root/"
          matchBinaries:
            - operator: In
              values:
                - "/usr/bin/bwrap"
          matchActions:
            - action: Post
